### ISSUE TITLE
RP launch is not ending

### ISSUE THREAD

**Issue by amalsgit** [reportportal/agent-postman#4]
Thanks guys for this RP Client.

When i tried running this with newman,  the results are getting pushed to RP. But the launch is not getting completed and I am forced to "Force Finish" the launch.

This is the command I used
```
>newman run Profile_Settings.postman_collection.json -e Dev_Env.json -r html,cli,junit,reportportal --reporter-html-template templates/htmlreqres.hbs --reporter-html-export API_Test_Report.html --reporter-junit-export Junit_report.xml --insecure --reporter-reportportal-debug=false --reporter-reportportal-endpoint=http://my_url/api/v1 --reporter-reportportal-token=my_token--reporter-reportportal-launch=API_Test --reporter-reportportal-project=MANUALEXECUTION
```

I get these errors in the console log:

```
(node:14452) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'realId' of undefined
    at helpers.getServerResult.then (C:\Users\ajayara\AppData\Roaming\npm\node_modules\newman-reporter-reportportal\node_modules\reportportal-client\lib\report-portal-client.js:293:49)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:14452) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 22)
(node:14452) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'realId' of undefined
    at helpers.getServerResult.then (C:\Users\ajayara\AppData\Roaming\npm\node_modules\newman-reporter-reportportal\node_modules\reportportal-client\lib\report-portal-client.js:293:49)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:14452) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 23)
{ error_code: 4001,
  message: 'Incorrect Request. [Field \'name\' shouldn\'t be null.] ' }
(node:14452) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'realId' of undefined
    at helpers.getServerResult.then (C:\Users\ajayara\AppData\Roaming\npm\node_modules\newman-reporter-reportportal\node_modules\reportportal-client\lib\report-portal-client.js:293:49)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:14452) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 24)
(node:14452) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'realId' of undefined
    at helpers.getServerResult.then (C:\Users\ajayara\AppData\Roaming\npm\node_modules\newman-reporter-reportportal\node_modules\reportportal-client\lib\report-portal-client.js:293:49)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:14452) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 25)
(node:14452) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'realId' of undefined
    at helpers.getServerResult.then (C:\Users\ajayara\AppData\Roaming\npm\node_modules\newman-reporter-reportportal\node_modules\reportportal-client\lib\report-portal-client.js:293:49)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:14452) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 26)
```

**Comment by amalsgit** [comment]
Hi @groov1kk 

Thanks for the input. However, even after adding the  --suppress-exit-code parameter the report portal run is not ending. Let me know if you require any additional information on the same,

**Comment by groov1kk** [comment]
Ok, I see.

Do you use asynchronous requests in your test scripts? I mean pm.sendRequest().

**Comment by amalsgit** [comment]
I am not using pm.sendRequest() in my tests. I do use pm.tests for the assertions. The below is a sample of the log which I can see in the newman console.

`Start test item 2kgawpatwjrqfiajf
Start test item 2kgawpatwjrqfib24
Start test item 2kgawpatwjrqfib25
Start test item 2kgawpatwjrqfib26                                                                                                                                                                                 \Error start item 2kgawpatwjrqfia2f:
{ error_code: 4001,
  message: 'Incorrect Request. [Field \'name\' shouldn\'t be null.] ' }
(node:14036) UnhandledPromiseRejectionWarning: #<Object>
(node:14036) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)
(node:14036) UnhandledPromiseRejectionWarning: #<Object>
(node:14036) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 11)
(node:14036) UnhandledPromiseRejectionWarning: #<Object>`

**Comment by groov1kk** [comment]
Could you send me an example of collection which you was tried to run in JSON format?

**Comment by DzmitryHumianiuk** [comment]
@amalsgit plz verify it is fixed

**Comment by murdoc-mos** [comment]
> Hello @amalsgit
> 
> You have to add -x or --suppress-exit-code parameter while running using CLI.
> 
> I have updated documentation. Thank you for your notice.

Why do we need to suppress exit codes? This seems to break our Circle CI workflow and it appears as though I can either have ReportPortal fail gracefully (with -x) or have Circle CI exit correctly.

**Comment by DzmitryHumianiuk** [comment]
@murdoc-mos do you have any proposal here?

**Comment by murdoc-mos** [comment]
> @DzmitryHumianiuk looking in to it, but I'm trying to gain context on _why_ ReportPortal has to suppress the exit codes.

**Comment by groov1kk** [comment]
From newman's documentation about suppres exit code:

_If present, allows overriding the default exit code from the current collection run, useful for bypassing collection result failures. Takes no arguments._

So, if there are test failures in postman script - newman reporter won't send finishing request to Report Portal and launch will never finished.

Add this flag to avoid the problem with unfinished launches.

**Comment by the-octopus** [comment]
@groov1kk  could you please explain how to force finish from testNG Java client. 

I have the same issue, when the TestNg execution is interrupted of failed foe some reasons , the launch is not finished.

Thanks.
