### ISSUE TITLE
"reportportal" reporter could not be loaded

### ISSUE THREAD

**Issue by Gageonea** [reportportal/agent-postman#6]
Installed newman
Installed newman-reporter-reportportal
Ran from a nodejs script just like in the documentation
Get this error:
`newman: "reportportal" reporter could not be loaded.
  please install reporter using npm`

Tried uninstalling and installing packages again, no change
Tries installing packages on a global level, no change

Any insight?

**Comment by groov1kk** [comment]
Hello

We've released a new version of this reporter inside of reportportal scope. You have to install reporter locally or globally with explicit scope specifying.

I have updated README. Following these new instruction everything has to be fine.

**Comment by Gageonea** [comment]
Well, followed the new README, still nothing 
`newman: "@reportportal/reportportal" reporter could not be loaded.
  please install reporter using npm`
Tried running it from node or bash scripts, still nothing

**Comment by groov1kk** [comment]
Are you trying to run tests programmatically?

If yes, have you added reporter's dependency into package.json? 

For example:

"dependencies": {
    "@reportportal/newman-reporter-reportportal": "0.0.20",
    "newman": "^4.4.1"
  }

**Comment by Gageonea** [comment]
Did just that. I've abandoned trying to run it via node script or bash script and so far I'm getting good result by using the docker option. I'll probably make a bash script to run inside the docker with a folder of all the images mounted to the docker image, or something like that.

**Comment by DzmitryHumianiuk** [comment]
@Gageonea can we close this issue?

**Comment by Gageonea** [comment]
yeah, managed to use the docker image
